### ISSUE TITLE
Sobre envio de imagens

### ISSUE THREAD

**Issue by GabrielCoelho** [gabrielbiga/ZapBot#1]
Olá!

Não sou tão bom em JS e por isso no que puder ajudar com ideias e conhecimentos diversos ajudarei. 
Estive conversando com o **@mathloureiro**  sobre o envio de imagens, devido a execução de um script com as falas do João Paulo (_Car@@%$%#$ eu sou um M#RD4 mermão_) e a intenção de enviar uma imagem após a execução do script no console. 

Para automatizar, sei que se você tem uma imagem copiada no seu _pasteboard_ e colar na área de mensagens do Whats-web, ela fica pronta para envio. 

Acredito que se desse para simular o _paste_ e simular o botão de envio da imagem, já conseguiremos dar continuidade ao **RoadMap**.

Atenciosamente,
Gabriel Coelho Soares
![bitmoji](https://render.bitstrips.com/v2/cpanel/9788649-312071007_10-s4-v1.png?transparent=1&palette=1&width=246)

##### Espero ter ajudado

**Comment by gabrielbiga** [comment]
E aí Gabriel, beleza? Valeu pela contribuição, as idéias sempre são importantes!

Pode fazer sentido, mas não sei se funcionaria por causa da limitação da API do browser. Pelo que vi, o sistema pega a foto e envia para o server em Base64. Talvez seria possível substituir isso e ter varias imagens em um array no JS pra mandar randomicamente por exemplo...

Seus bots dos memes ficaram bem daora! Se quiser, pode portar para o ZapBot e enviar via pull request la pra dentro da pasta examples. A implementação de enviar é idêntica a que o @mathloureiro fez.

Vou deixar a issue aberta pra futura discussão. Abraço!

**Comment by GabrielCoelho** [comment]
## Algumas perguntas interessantes no **StackOverflow** e outras fontes
Fui procurar sobre colar textos do **clipboard** (_tinha chamado de pasteboard anteriormente pois não lembrava o termo real_) com funções JavaScript. 

Inicialmente cheguei nesses links:
+ [JavaScript get Clipboard Data and paste as plain Text][stack01]
+ [JavaScript copy image to clipboard][stack02]

### No Primeiro link
tem uma ótima explicação feita pelo **Nico Burns**, com duas soluções para o problema proposto. 

### No Segundo link
é um problema mais parecido com o que precisamos, e a partir dele cheguei em outro link: [O Guia definitivo de como copiar e colar com JavaScript][lucidchart]

Não parece ser tão complicado, a parte complicada mesmo será na hora de simular o envio de imagens pelo webWhats. 

[stack01]: https://stackoverflow.com/questions/2176861/javascript-get-clipboard-data-on-paste-event-cross-browser
[stack02]: https://stackoverflow.com/questions/33175909/copy-image-to-clipboard
[lucidchart]: https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by JulyanoF** [comment]
@GabrielCoelho opa, logo mais vou tentar fazer a implementação no script do @mathloureiro, valeu.
Se der certo, posto o resultado aqui para o @gabrielbiga implementar nesse bot dele.

**Comment by gabrielbiga** [comment]
Valeu pela referência @GabrielCoelho, vou dar uma olhada com certeza... E muito legal @JulyanoF! Qualquer update posta aqui. Se eu tiver algum resultado posto aqui pra vocês também.

**Comment by JulyanoF** [comment]
@gabrielbiga @GabrielCoelho pelo que dei uma lida naquele tutorial ali do "LucidChart", só é possível fazer isso usando a extensão deles, pois nativamente não é possível acessar o clipboard :/

**Comment by JulyanoF** [comment]
[http://caniuse.com/#feat=clipboard](http://caniuse.com/#feat=clipboard)
Chrome 42+, Opera 29+ and Firefox 41+ support clipboard reading/writing only when part of a user action (click, keydown, etc). 
Então, tem que ter alguma ação do usuário para poder acessar o clipboard :( não rola automatizar

**Comment by GabrielCoelho** [comment]
@JulyanoF nem se simulássemos a _user action_? Estou focando os estudos em JS agora e, assim que possível, começo a tentar simular algumas coisas. Assim que eu conseguir, começo a procurar mais sobre o clipboard!

**Comment by JulyanoF** [comment]
@GabrielCoelho acredito que não, tem que, de fato, ter alguma ação do usuário (nem que seja um click, apertar algum botão)

**Comment by andrevandal** [comment]
Pelo que li do proposto e pela conversa, acredito que a melhor maneira para resolver isso seria conseguir achar o evento que é disparado para envio da imagens do navegador para o servidor do whatsapp e disparar essa ação pelo bot.
